In [2]:
import pandas as pd
import numpy as np

In [6]:
from google.colab import files

uploaded = files.upload()

df = pd.read_csv("Day7_Student_Dataset.csv")

df

Saving Day7_Student_Dataset.csv to Day7_Student_Dataset.csv

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar
10,1011,Vivaan Kapoor,20,AI,91.0,94.0,Jaipur
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
12,1013,Rahul Das,23,Data Science,72.0,81.0,Kolkata
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
14,1015,Karan Joshi,20,Computer Science,77.0,85.0,Chandigarh
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [7]:
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [8]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [9]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
13,1014,Sana Malik,18,AI,89.0,92.0,NaN
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad

In [12]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 25
Number of columns: 7

In [11]:
df.shape

(25, 7)

In [13]:
print("Column names:")
print(df.columns)

Column names:
Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

In [14]:
print("Dataset Index:")
print(df.index)

Dataset Index:
RangeIndex(start=0, stop=25, step=1)

In [15]:
print("Data Types:")
print(df.dtypes)

Data Types:
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

In [17]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

In [18]:
df.describe(include="object")

                Name        Course      City
count             25            25        24
unique            25             3        13
top     Aarav Sharma  Data Science  Srinagar
freq               1             9         6

In [19]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [20]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing value percentage:")
print(missing_percentage)

Missing value percentage:
Student_ID               0.0
Name                     0.0
Age                      0.0
Course                   0.0
Marks                    4.0
Attendance_Percentage    4.0
City                     4.0
dtype: float64

In [21]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean() * 100).round(2)
})

missing_summary

                       Missing Values  Missing Percentage
Student_ID                          0                 0.0
Name                                0                 0.0
Age                                 0                 0.0
Course                              0                 0.0
Marks                               1                 4.0
Attendance_Percentage               1                 4.0
City                                1                 4.0

In [22]:
print("DATASET SUMMARY")
print("-----------------------------")
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])
print("Total Missing Values:", df.isnull().sum().sum())

print("\nFeatures:")
for column in df.columns:
    print("-", column)

DATASET SUMMARY
-----------------------------
Number of Rows: 25
Number of Columns: 7
Total Missing Values: 3

Features:
- Student_ID
- Name
- Age
- Course
- Marks
- Attendance_Percentage
- City

In [23]:
for column in df.columns:
    print("\n", column)
    print(df[column].unique())

 Student_ID
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025]

 Name
['Aarav Sharma' 'Zoya Khan' 'Rohan Mehta' 'Ananya Singh' 'Kabir Ali'
 'Ishita Gupta' 'Aditya Verma' 'Sara Ahmed' 'Arjun Nair' 'Mehak Bhat'
 'Vivaan Kapoor' 'Aisha Mir' 'Rahul Das' 'Sana Malik' 'Karan Joshi'
 'Hiba Sheikh' 'Dev Patel' 'Manya Rao' 'Yusuf Dar' 'Priya Menon'
 'Aman Kumar' 'Alina Shah' 'Nikhil Sood' 'Maryam Khan' 'Reyansh Jain']

 Age
[19 20 18 21 22 23]

 Course
['Data Science' 'AI' 'Computer Science']

 Marks
[87. 92. 76. 81. 69. 88. 95. 73. 84. 79. 91. 68. 72. 89. 77. 94. 86. 70.
 nan 90. 74. 96. 78. 85. 80.]

 Attendance_Percentage
[91. 95. 82. 88. 76. 93. 97. nan 86. 90. 94. 72. 81. 92. 85. 96. 89. 74.
 87. 78. 98. 83. 84.]

 City
['Srinagar' 'Delhi' 'Mumbai' 'Lucknow' 'Bengaluru' 'Pune' 'Hyderabad'
 'Kochi' 'Jaipur' 'Kolkata' nan 'Chandigarh' 'Ahmedabad' 'Chennai']